### ISSUE TITLE
Wrong JBang version is downloaded

### ISSUE THREAD

**Issue by frederikb** [jbangdev/setup-jbang#2]
### Problem / Observed Behavior
The action supports has a `version` parameter to specify the version of JBang to download.
This does not work and the action always downloads the latest version instead.

### Expected Behavior
The specified version of JBang is downloaded.

### How to replicate
```
- name: Setup JBang
  uses: jbangdev/setup-jbang@v0.1.1
  with:
    version: v0.113.0
```

It will download `v0.116.0`.

### Analysis

The `version` parameter is not exposed to the shell/PowerShell script, which expect the environment variable `$JBANG_DOWNLOAD_VERSION` to be set. 

In addition we must refrain from setting this env in case `version` is set to `latest` (as it is by default).

See:
- https://raw.githubusercontent.com/jbangdev/jbang/master/src/main/scripts/jbang
- https://raw.githubusercontent.com/jbangdev/jbang/master/src/main/scripts/jbang.ps1

**Comment by maxandersen** [comment]
Good find!
